--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BeeAZ-pm-pl/FormBuilderX
build-by-default: true
branches:
- master
projects:
  FormBuilderX:
    path: ""
    model: virion
    type: library
...
